//3rd  guy
                'name': '3rd\x20Person',
                'varN': 'thirdPerson',
                'def': !0x1,
                'bool': !0x0
//health bar
                'name': 'Health\x20Regen',
                'varN': 'hpRegen',
                'def': !0x0,
                'bool': !0x0
//name [See names]
                'name': 'Hide\x20Nametags',
                'varN': 'nameTags',
                'def': !0x1,
                'bool': !0x0
                //the names will be hidden. Change 1 to 0 to be able see through walls.
//Health range idk why I took it but ok?
                'name': 'Health\x20Regen',
                'varN': 'hpRegen',
                'def': !0x0,
                'bool': !0x0
//auto bhop
                'name': 'Auto\x20Jump',
                'varN': 'autoJump',
                'def': !0x1,
                'bool': !0x0
//auto slide
                'name': 'Sliding',
                'varN': 'canSlide',
                'def': !0x0,
                'bool': !0x0
//auto aim to head.
                'name': 'Headshots\x20Only',
                'varN': 'headshotOnly',
                'dontChange': !0x0,
                'def': !0x1,
                'bool': !0x0
//health my team
                'name': 'Health\x20Multiplier',
                'varN': 'healthMlt',
                'dontChange': !0x0,
                'def': 0x1,
                'max': 0x3,
                'min': 0.1,
                'step': 0.1
                //maybe important?
//scale (hrt was using it atleast?)
                'name': 'Time\x20Scale',
                'varN': 'deltaMlt',
                'dontChange': !0x0,
                'def': 0x1,
                'max': 1.5,
                'min': 0.1,
                'step': 0.1
//hit box scale
                'name': 'Hitbox\x20Scale',
                'varN': 'hitBoxPad',
                'dontChange': !0x0,
                'def': 0x1,
                'max': 0x1,
                'min': 0x0,
                'step': 0.1
//Jumping force if needed?
                'name': 'Jump\x20Force',
                'varN': 'jumpMlt',
                'dontChange': !0x0,
                'def': 0x1,
                'max': 0x3,
                'min': 0.1,
                'step': 0.1

// use "varN" to find values from game.js
// this variables maybe are important atleast ESP if anyone needs it?
